name: Continous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "*.py"
      - "pyproject.toml"
      - "uv.lock"
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        name: Checkout
      - name: Install uv
        uses: astral-sh/setup-uv@a7e15805d229f8677c5ddf08590a8cb972658599
        with:
          cache-dependency-glob: "uv.lock"
          enable-cache: true
          version: "0.5.1"
      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --locked --no-group dev --group lint
      - name: Check code format with Ruff
        run: make check-format
      - name: Lint code with Ruff
        run: make check-lint
      - name: Check types with Mypy
        run: make check-types
  
  test:
    name: Tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        name: Checkout
      - name: Install uv
        uses: astral-sh/setup-uv@a7e15805d229f8677c5ddf08590a8cb972658599
        with:
          cache-dependency-glob: "uv.lock"
          enable-cache: true
          version: "0.5.1"
      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --locked --no-group dev --group test
      - name: Run tests with pytest
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673
        with:
          token: ${{ secrets.CODECOV_TOKEN }}